require:
  - rubocop-rails
AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - "bin/*"
    - "db/migrate/*.rb"
    - "db/schema.rb"
    - "log/**/*"
    - "node_modules/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
Layout/HashAlignment:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/RescueEnsureAlignment:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: compact
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"
Lint/SuppressedException:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/FileName:
  Exclude:
    - "Gemfile"
Naming/PredicateName:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  PreferredName: "err"
Rails:
  Enabled: true
Rails/Delegate:
  Enabled: false
Rails/FilePath:
  EnforcedStyle: arguments
Rails/FindBy:
  Enabled: false
Rails/FindEach:
  Enabled: false
Rails/HelperInstanceVariable:
  Enabled: false
Rails/InverseOf:
  Enabled: true
Rails/OutputSafety:
  Enabled: false
Security/Open:
  Enabled: false
Style/Attr:
  Exclude:
    - "app/graphql/**/*"
Style/BlockDelimiters:
  Enabled: false
# Style/ClassAndModuleChildren:
#   EnforcedStyle: nested
#   Exclude:
#     - "config/application.rb"
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: ruby19
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MixinUsage:
  Enabled: true
  Exclude:
    - "db/seeds.rb"
Style/NonNilCheck:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma